import Foundation

/// Temps explicitement indiqués dans RECETTES.pdf, en minutes.
enum RecipePreparationTimes {
    static let byID: [String: Int] = [
        "paella-valence": 45,
        "salacrevette": 45,
        "verrines-crevettes": 15,
        "roti-orlof": 15,
        "ufs-a-la-neige": 5,
        "barbecue-poulet": 120,
        "sashimi": 30,
        "choux-vert-a-la": 30,
        "paella": 45,
        "papillotte-poisson": 15,
        "veloute-potiron": 30,
        "veloute-petits-pois": 30,
        "encornets": 15,
        "rouleaux-de": 30,
        "sauce-aux-oignons": 10,
        "couscous-merguez": 10,
        "pot-au-feu": 30,
        "chirachi-au-riz": 60,
        "tortilla-salade": 10,
        "tarte-pesto-legumes": 30,
        "mont-dor-au-four": 10,
        "gateau-aux-pommes": 25,
        "pad-thai": 20,
        "muffins-au-saint": 30,
        "muffins": 30,
        "gauffres": 30,
        "boudin-pomme":30,
        "gateau-a-la-creme": 10,
        "gateau-semoule": 30,
        "canneles-bordelais": 75,
        "kouign-amann-de": 30,
        "pate-a-pizza": 30,
        "choux-vert-a-la-2": 30,
        "gratin-patates": 20,
        "feuillete-epinards": 20,
        "charlotte": 20,
        "taboule": 20,
        "saumon-tandoori": 20,
        "pommes-au-four": 20,
        "saute-porc-au": 15,
        "mini-muffins-a-la": 15,
        "mini-muffins-aux": 15,
        "couscous-marocain": 30,
        "soupe-legumes": 30,
        "soupe-thai-crevette": 30,
        "soupe-courgette": 15,
        "guacamole": 15,
        "rillette-jambon": 10,
        "endive-jambon": 75,
        "blanquette-mer": 60,
        "puree-pois-casse": 60,
        "puree": 60,
        "veloute-corail": 30,
        "veloute-lentille": 45,
        "veloute-champignon": 30,
        "risotto-gorgonzola": 45,
        "saumon-brocolis": 45,
        "carottes-vichy": 50,
        "fondue-poireau": 40,
        "filet-moutarde": 45,
        "puree-potiron": 60,
        "gaspacho": 120,
        "soupe-chinoise": 45,
        "poulet-amande": 50,
        "chevre-chaud": 15
    ]
}
