import Foundation

/// Pages du catalogue RECETTES.PDF. Les numéros sont ceux affichés dans le PDF (base 1).
enum RecipePDFPages {
    static let byID: [String: Int] = [
        "zarzuela": 3,
        "perles-japon-coco": 4,
        "sauce-barbecue-bbq": 5,
        "paella-valence": 6,
        "salacrevette": 7,
        "verrines-crevettes": 10,
        "roti-orlof": 10,
        "oeufs-a-la-neige": 12,
        "sashimi": 15,
        "choux-vert-a-la": 58,
        "paella": 23,
        "risotto-potiron": 25,
        "veloute-potiron": 27,
        "veloute-petits-pois": 28,
        "encornets": 29,
        "rouleaux-de": 30,
        "sauce-aux-oignons": 31,
        "couscous-merguez": 32,
        "pot-au-feu": 33,
        "chirachi-au-riz": 34,
        "punch-planteur": 37,
        "sangria-rouge": 38,
        "lasagne-poisson": 40,
        "quiche-lorraine": 41,
        "tarte-pesto-legumes": 43,
        "mont-dor-au-four": 45,
        "gateau-aux-pommes": 46,
        "pad-thai": 47,
        "muffins-au-saint": 49,
        "muffins": 50,
        "gauffres": 51,
        "gateau-a-la-creme": 52,
        "gateau-semoule": 53,
        "canneles-bordelais": 54,
        "kouign-amann-de": 55,
        "pate-a-pizza": 56,
        "gratin-patates": 60,
        "feuillete-epinards": 61,
        "taboule": 66,
        "roules-au-chorizo": 67,
        "saumon-tandoori": 69,
        "pommes-au-four": 70,
        "grenailles-a-lail-en": 71,
        "saute-porc-au": 72,
        "mini-muffins-aux": 75
    ]
    
    static func id(forRecipeName name: String) -> String? {
        let idsByName: [String: String] = [
            "Zarzuela": "zarzuela",
            "Perles Japon Coco": "perles-japon-coco",
            "Sauce Barbecue": "sauce-barbecue-bbq",
            "Paella Valence": "paella-valence",
            "Salade de Crevettes": "salacrevette",
            "Verrines Crevettes": "verrines-crevettes",
            "Roti Orlof": "roti-orlof",
            "Œufs A La Neige Coulis de mangue": "oeufs-a-la-neige",
            "Sashimi": "sashimi",
            "Choux Vert A La Viande": "choux-vert-a-la",
            "Paella": "paella",
            "Risotto Potiron": "risotto-potiron",
            "Veloute Potiron": "veloute-potiron",
            "Veloute Petits Pois": "veloute-petits-pois",
            "Encornets au balsamique": "encornets",
            "Rouleaux De Printemps": "rouleaux-de",
            "Sauce Aux Oignons & raisins secs - Couscous": "sauce-aux-oignons",
            "Couscous Aux Merguez": "couscous-merguez",
            "Pot-Au-Feu": "pot-au-feu",
            "Chirachi Au Riz": "chirachi-au-riz",
            "Punch Planteur": "punch-planteur",
            "Sangria Rouge": "sangria-rouge",
            "Lasagne Poisson": "lasagne-poisson",
            "Quiche Lorraine": "quiche-lorraine",
            "Tarte Pesto Legumes": "tarte-pesto-legumes",
            "Mont D’Or Au Four": "mont-dor-au-four",
            "Gateau Aux Pommes": "gateau-aux-pommes",
            "Pad Thaï": "pad-thai",
            "Muffins Au Saint Nectaire": "muffins-au-saint",
            "Muffins": "muffins",
            "Gauffres": "gauffres",
            "Gateau A La Creme de marron": "gateau-a-la-creme",
            "Gateau Semoule": "gateau-semoule",
            "Canneles Bordelais": "canneles-bordelais",
            "Kouign Amann": "kouign-amann-de",
            "Pate A Pizza": "pate-a-pizza",
            "Gratin Patates Douces": "gratin-patates",
            "Feuilleté Epinards & Féta": "feuillete-epinards",
            "Taboule": "taboule",
            "Roules Au Chorizo": "roules-au-chorizo",
            "Saumon Tandoori": "saumon-tandoori",
            "Pommes Au Four": "pommes-au-four",
            "Grenailles A L’Ail En": "grenailles-a-lail-en",
            "Saute Porc Au Chou Vert": "saute-porc-au",
            "Mini-Muffins Aux pépites de Chocolat": "mini-muffins-aux"
        ]
        return idsByName[name]
    }
}
